### ISSUE TITLE
upgrade to scala 2.12

### ISSUE THREAD

**Issue by ayoub-benali** [ayoub-benali/signal-desktop-client#2]
upgrade to scala 2.12 once 
- [x] this [scalafxml PR](https://github.com/vigoo/scalafxml/pull/22) is merged
- [x] this [issue with slick](https://github.com/slick/slick/issues/1572) is fixed

**Comment by snadorp** [comment]
Slick has been upgraded to 2.12. There's no blocker anymore.

**Comment by snadorp** [comment]
This has been fixed by #34
